name: teach-act-seq-learners
channels:
  - pytorch
dependencies:
  - python=3.7
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.1.1
  - scikit-learn=0.21.3
  - pytorch=1.2.0
  - pip=19.2.3
  - pip:
    - lifelines==0.22.6
    - pyro-ppl==0.3.0
